#!/usr/bin/env bash
# Transfers a file from our client to a server

if [ "$4" == "" ]
then 
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    host="$3@$2:~/"
    scp -o StrictHostKeyChecking=no -i $4 $1 $host
fi
