#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Holberton School"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
